version: '3'

services:
  mysql_dbms:
    image: mysql/mysql-server
    container_name: mysql_dbms
    environment:
      MYSQL_ROOT_PASSWORD:
    ports:
      - "3306:3306"
    volumes:
      - /data/mysql:/var/lib/mysql
      - ./init-sql:/docker-entrypoint-initdb.d
    networks:
      network_app:
        aliases:
          - mysql_dbms

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: pma
    environment:
      PMA_HOST: mysql_dbms
      PMA_PORT: 3306
      PMA_ARBITRARY: 1
    restart: always
    ports:
      - 8081:80

  sparta-vhs-app:
    build: .
    container_name: sparta-vhs-app
    restart: always
    ports:
      - 8080:8080
    volumes:
      - ./application.properties:/usr/src/app/src/main/resources/application.properties
    networks:
      network_app:
        aliases:
          - sparta-vhs-app

networks:
  network_app:
