version: '3'

services:
  vhs_mysql_dbms:
    image: mysql/mysql-server
    container_name: vhs_mysql_dbms
    environment:
      MYSQL_ROOT_PASSWORD:
    ports:
      - "3306:3306"
    volumes:
      - /data/vhs_mysql_dbms:/var/lib/mysql
      - ./init-sql:/docker-entrypoint-initdb.d
    networks:
      network_app:
        aliases:
          - vhs_mysql_dbms

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: vhs_pma
    environment:
      PMA_HOST: vhs_mysql_dbms
      PMA_PORT: 3306
      PMA_ARBITRARY: 1
    restart: always
    ports:
      - 8081:80

  sparta-vhs-app:
    build: .
    container_name: sparta-vhs-app
    restart: always
    ports:
      - 8080:8080
    volumes:
      - ./application.properties:/usr/src/app/src/main/resources/application.properties
    networks:
      network_app:
        aliases:
          - sparta-vhs-app

networks:
  network_app:
